version: "3.8"

services:
  user_service:
    container_name: zomato_user_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/zomato
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - db
    networks:
      - zomato_network
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

  pgadmin:
    container_name: zomato_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - zomato_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_zomato
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zomato_network

  db: # This should be correctly indented
    container_name: zomato_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zomato
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - zomato_network

networks:
  zomato_network:
    driver: bridge

volumes:
  pg_data:
